picolibc: Place C++ headers in a subdir of the libc headers
crosstool-ng/crosstool-ng pull request #1863
Opened 2022-12-01 12:55 UTC by jnohlgard

This changes the picolibc libstdc++ configuration to place the C++ headers under the same base include path that picolibc uses for the C headers.

2022-12-02 07:29 UTC, cpackham requested changes
Could you put a bit of info in the commit message. The PR only exists on github so we want to get useful info in the commit message which will go with the repo wherever it is hosted in the future.

2022-12-02 07:29 UTC, cpackham commented
@keith-packard any opinion on this?

2022-12-02 10:06 UTC, jnohlgard commented
@cpackham that makes sense. I have pushed an updated commit with a bit more explanation in the commit message.

2022-12-03 02:28 UTC, keith-packard commented
> @keith-packard any opinion on this?

Seems like this will require changes to the picolibc.specs file so that the right C++ headers will be used? Probably better than assuming they don't depend on the underlying C library though?

2023-03-08 04:06 UTC, cpackham commented
@keith-packard between #1901 and #1908 is this still needed?

2023-03-08 04:51 UTC, jnohlgard commented
Let's close this for now. I will not have the time to rework this to actually do what I originally intended.

2023-03-08 04:51 UTC, closed without merging