Add mingw-w64 v10.0.0
crosstool-ng/crosstool-ng pull request #1883
Opened 2023-01-26 16:04 UTC by mid-kid

2023-01-26 16:04 UTC, mid-kid commented
Fixes https://github.com/crosstool-ng/crosstool-ng/issues/1880

2023-01-30 07:57 UTC, cpackham requested changes

2023-01-30 07:57 UTC, cpackham commented on config/global/paths.in
> +    default "${HOME}/.local/opt/cross/src"
This shouldn't be included

2023-01-30 07:57 UTC, cpackham commented on maintainer/manage-packages.sh
> +available in crosstool-NG and check that the patches apply cleanly.
Ideally the typo fix would be a separate commit.

2023-01-30 08:13 UTC, cpackham commented
Also the commit needs a reasonable message and sign-off.

2023-01-31 07:46 UTC, cpackham approved these changes

2023-02-01 08:58 UTC, merged